repos:
  - repo: https://github.com/ambv/black
    rev: 19.3b0
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
      - id: flake8
        args: ['--config=tox.ini']
      - id: requirements-txt-fixer
      - id: end-of-file-fixer
      - id: check-yaml
        args: ['--unsafe']
        files: .*\.(yaml|yml)$
        args: ['--unsafe']
